### PR TITLE
remove build dependencies beta001.yml

### PR DESCRIPTION
**Pull request by andrew-lele**

### CODE REVIEW

**Comment by hhratcliffe** [comment]
smh leaving me out as a reviewer. DENIED

**Comment by andrew-lele** [comment]
> smh leaving me out as a reviewer. DENIED

fk u i hope ur environment never gets built

**Comment by mity1** [comment]
Is this update for windows or for yourself? I already pushed something for windows yesterday called dev01.yaml

**Comment by andrew-lele** [comment]
> Is this update for windows or for yourself? I already pushed something for windows yesterday called dev01.yaml

its for all OS so windows, macos and linux 

i think u pushed something onto ur branch but this one is straight to develop

**Comment by mity1** [comment]
Oh hm nah it’s in develop. Is the prefix not important?

**Comment by andrew-lele** [comment]
> Oh hm nah it’s in develop. Is the prefix not important?

bruh they're the same file LOL im just gonna close the PR. drop beta prefix and just use dev01 to configure environments from now on

**Pull request closed without merging**
